"""Initial baseline tables

Revision ID: 720e5a6265ef
Revises: 
Create Date: 2026-08-16 21:12:34.084895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720e5a6265ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_url_length', sa.Integer(), nullable=False),
    sa.Column('max_special_chars', sa.Integer(), nullable=False),
    sa.Column('max_subdomains', sa.Integer(), nullable=False),
    sa.Column('max_entropy', sa.Float(), nullable=False),
    sa.Column('block_ip_hostnames', sa.Boolean(), nullable=False),
    sa.Column('flag_sensitive_keywords', sa.Boolean(), nullable=False),
    sa.Column('flag_brand_spoofing', sa.Boolean(), nullable=False),
    sa.Column('flag_non_standard_ports', sa.Boolean(), nullable=False),
    sa.Column('flag_suspicious_tlds', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_rules_id'), 'config_rules', ['id'], unique=False)
    op.create_table('inspection_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('is_phishing', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('ml_probability', sa.Float(), nullable=True),
    sa.Column('ml_model_version', sa.String(length=50), nullable=True),
    sa.Column('flags_count', sa.Integer(), nullable=False),
    sa.Column('override_verdict', sa.String(length=50), nullable=True),
    sa.Column('fired_rules', sa.JSON(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inspection_phishing_time', 'inspection_logs', ['is_phishing', 'created_at'], unique=False)
    op.create_index('idx_inspection_verdict_time', 'inspection_logs', ['verdict', 'created_at'], unique=False)
    op.create_index(op.f('ix_inspection_logs_created_at'), 'inspection_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_inspection_logs_domain'), 'inspection_logs', ['domain'], unique=False)
    op.create_index(op.f('ix_inspection_logs_id'), 'inspection_logs', ['id'], unique=False)
    op.create_index(op.f('ix_inspection_logs_is_phishing'), 'inspection_logs', ['is_phishing'], unique=False)
    op.create_index(op.f('ix_inspection_logs_verdict'), 'inspection_logs', ['verdict'], unique=False)
    op.create_table('whitelist_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('added_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whitelist_domains_domain'), 'whitelist_domains', ['domain'], unique=True)
    op.create_index(op.f('ix_whitelist_domains_id'), 'whitelist_domains', ['id'], unique=False)
    op.create_table('extracted_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('url_length', sa.Integer(), nullable=False),
    sa.Column('domain_length', sa.Integer(), nullable=False),
    sa.Column('subdomain_count', sa.Integer(), nullable=False),
    sa.Column('special_char_count', sa.Integer(), nullable=False),
    sa.Column('entropy', sa.Float(), nullable=False),
    sa.Column('has_ip', sa.Integer(), nullable=False),
    sa.Column('contains_sensitive_keyword', sa.Integer(), nullable=False),
    sa.Column('is_https', sa.Integer(), nullable=False),
    sa.Column('raw_feature_vector', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id')
    )
    op.create_index(op.f('ix_extracted_features_id'), 'extracted_features', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_features_id'), table_name='extracted_features')
    op.drop_table('extracted_features')
    op.drop_index(op.f('ix_whitelist_domains_id'), table_name='whitelist_domains')
    op.drop_index(op.f('ix_whitelist_domains_domain'), table_name='whitelist_domains')
    op.drop_table('whitelist_domains')
    op.drop_index(op.f('ix_inspection_logs_verdict'), table_name='inspection_logs')
    op.drop_index(op.f('ix_inspection_logs_is_phishing'), table_name='inspection_logs')
    op.drop_index(op.f('ix_inspection_logs_id'), table_name='inspection_logs')
    op.drop_index(op.f('ix_inspection_logs_domain'), table_name='inspection_logs')
    op.drop_index(op.f('ix_inspection_logs_created_at'), table_name='inspection_logs')
    op.drop_index('idx_inspection_verdict_time', table_name='inspection_logs')
    op.drop_index('idx_inspection_phishing_time', table_name='inspection_logs')
    op.drop_table('inspection_logs')
    op.drop_index(op.f('ix_config_rules_id'), table_name='config_rules')
    op.drop_table('config_rules')
    # ### end Alembic commands ###
